package ist.depchain.client;

/* NETWORK UTILS */
import ist.depchain.network.PerfectLink;
import ist.depchain.network.StubbornLink;
import ist.depchain.network.UdpFairLossLink;
import ist.depchain.network.utils.Config;

/* ClASSES GENERATED BY PROTOBUF */
import ist.depchain.common.ClientRequest;
import ist.depchain.common.ClientResponse;
import ist.depchain.common.Command;

/* ATOMIC COUNTER */
import java.util.concurrent.atomic.AtomicInteger;

public class DepChainClient {
    private final UdpFairLossLink fairLossLink;
    private final StubbornLink stubbornLink;
    private final PerfectLink perfectLink;
    private final Config config;
    private final AtomicInteger counter = new AtomicInteger(0);

    public DepChainClient(Config config) {
        this.config = config;
        fairLossLink = new UdpFairLossLink(config);
        stubbornLink = new StubbornLink(config, fairLossLink);
        perfectLink = new PerfectLink(config, stubbornLink, fairLossLink);
    }

    public void append(String data){
        int reqId = counter.incrementAndGet();

        Command cmd = Command.newBuilder()
                .setType("append")
                .setData(data)
                .build();

        ClientRequest cltReq = ClientRequest.newBuilder()
                                            .setClientId(config.getSelfId())
                                            .setRequestId(reqId)
                                            .setCommand(cmd)
                                            .build();

        System.out.println("[SENT] Client " + config.getSelfId() + " Request Id: " + reqId + " Data: " + data);

        byte[] payload = cltReq.toByteArray();
        for(String target : config.getProcesses().keySet()) {
            if(!target.equals(config.getSelfId())) {
                perfectLink.send(target, payload); // TODO PROBLEM: each time send() is called, seq is incremented (will be solved with broadcast implementation)
            }
        }
    }

    public void start() {
        perfectLink.registerReceiver((sourceId, data) -> {
            try {
                ClientResponse cltResponse = ClientResponse.parseFrom(data);

                System.out.println("[RECEIVED] Response from: " + sourceId);
                System.out.println("[RECEIVED] Id of request: " + cltResponse.getRequestId());
                System.out.println("[RECEIVED] State: " + cltResponse.getCommitted());
            }catch(Exception e) {
                System.out.println("[ERROR] Error while processing request: " + e.getMessage());
            }
        });

        perfectLink.start();
    }

    public void stop() {
        perfectLink.stop();
    }
}
