package ist.depchain.client;

/* NETWORK UTILS */
import ist.depchain.network.PerfectLink;
import ist.depchain.network.StubbornLink;
import ist.depchain.network.UdpFairLossLink;
import ist.depchain.network.utils.ProcessInfo;
import ist.depchain.network.utils.ProcessConfig;
import ist.depchain.network.utils.ArtificialFaultConfig;

/* ClASSES GENERATED BY PROTOBUF */
import ist.depchain.common.ClientRequest;
import ist.depchain.common.ClientResponse;
import ist.depchain.common.Command;

/* ATOMIC COUNTER */
import java.util.concurrent.atomic.AtomicInteger;

public class DepChainClient {
    private final PerfectLink perfectLink;
    private final ProcessConfig config;
    private final String clientID;
    private final AtomicInteger counter = new AtomicInteger(0);

    public DepChainClient(String clientID, ProcessConfig config, ArtificialFaultConfig faultConfig) {
        this.clientID = clientID;
        this.config = config;

        ProcessInfo selfInfo = config.getProcesses().get(clientID);
        UdpFairLossLink udpFairLossLink = new UdpFairLossLink(selfInfo, config, faultConfig);
        StubbornLink stubbornLink = new StubbornLink(udpFairLossLink, 1000);
        perfectLink = new PerfectLink(clientID, stubbornLink, udpFairLossLink);
    }

    public void append(String data){
        int reqId = counter.incrementAndGet();

        Command cmd = Command.newBuilder()
                .setType("append")
                .setData(data)
                .build();

        ClientRequest cltReq = ClientRequest.newBuilder()
                                            .setClientId(clientID)
                                            .setRequestId(reqId)
                                            .setCommand(cmd)
                                            .build();

        System.out.println("[SENT] Client " + clientID + " Request Id: " + reqId + " Data: " + data);

        byte[] payload = cltReq.toByteArray();
        for(String target : config.getProcesses().keySet()) {
            if(!target.equals(clientID)) {
                perfectLink.send(target, payload); // TODO PROBLEM: each time send() is called, seq is incremented (will be solved with broadcast implementation)
            }
        }
    }

    public void start() {
        perfectLink.registerReceiver((sourceId, data) -> {
            try {
                ClientResponse cltResponse = ClientResponse.parseFrom(data);

                System.out.println("[RECEIVED] Response from: " + sourceId);
                System.out.println("[RECEIVED] Id of request: " + cltResponse.getRequestId());
                System.out.println("[RECEIVED] State: " + cltResponse.getCommitted());
            }catch(Exception e) {
                System.out.println("[ERROR] Error while processing request: " + e.getMessage());
            }
        });

        perfectLink.start();
    }

    public void stop() {
        perfectLink.stop();
    }
}
