syntax = "proto3";

package ist.depchain;

option java_package = "ist.depchain.common";
option java_outer_classname = "DepchainProto";
option java_multiple_files = true;

// Network Layer

message Handshake {
    bytes ecdhPublicKey = 1;
    bool is_reply = 2;
}

message Envelope {
    string sender_id = 1; // e.g., "replica1", "replica2", ...
    uint64 sequence_number = 2; // unique per sender

    oneof content {
        bytes payload = 3; // serialized message (e.g., ClientRequest, HotStuffMessage, etc.)
        Ack ack = 4;
        Handshake handshake = 5;
    }
}

message Ack {
    string original_sender = 1; // who sent the original message being acknowledged
    uint64 original_sequence_number = 2; // sequence number of the original message being acknowledged
}

// Client <-> Replica Messages

message ApplicationMessage { // serves to simplify the message handling logic by MessageHandler
    oneof content {
        ClientRequest  client_request   = 1;
        HotStuffMessage hotstuff_message = 2;
    }
}

message Command {
    string type = 1; // e.g., "append", "read", etc.
    string data = 2; // e.g., for "append", the string to append
    string client_id = 3; 
    int32  request_id = 4;
}

message ClientRequest {
    string client_id = 1;
    int32 request_id = 2; // unique per client_id
    Command command = 3; // e.g., "append", "read", etc.
}

message ClientResponse {
    string client_id = 1;
    int32 request_id = 2; // matches the request_id of the ClientRequest
    bool committed = 3;
    bytes block_id = 4;
}

// Replica <-> Replica Messages (HotStuff)

message HotStuffMessage{
    enum Type{                // [Pag 6, Data Structures, Messages]
        NEW_VIEW = 0;
        PREPARE = 1;
        PRE_COMMIT = 2;
        COMMIT = 3;
        DECIDE = 4;
    }
    Type type = 1;            // [Line 2]  - m.type
    int32 view_number = 2;    // [Line 3]  - m.viewNumber
    Block block = 3;          // [Line 4]  - m.node
    QC justify = 4;           // [Line 5]  - m.justify (optional)
    bytes partial_sig = 5;    // [Line 9]  - m.partialSig (optional - sent only by replicas)
}

message Block {
    bytes id = 1;          // Unique digest of block - Cryptographic Security reasons
    bytes parent_id = 2;   // [Line 12] - b.parent
    Command command = 3;   // [Line 13] - b.cmd, command included in this block
}

message QC {
    HotStuffMessage.Type type = 1;   // [Line 16] - qc.type
    int32 view_number = 2;           // [Line 17] - qc.viewNumber
    bytes block_id = 3;              // [Line 18] - qc.node
    bytes threshold_sig = 4;         // [Line 19] - qc.sig, signature aggregated from a quorum of replicas (threshold signature)
}